name: Lint

on:
  push:
    paths:
      - "**.lua"
      - ".github/workflows/lint.yml"
  pull_request:
    paths:
      - "**.lua"
      - ".github/workflows/lint.yml"

jobs:
  lint:
    uses: PulsarFW/.github/.github/workflows/lint.yml@main
    with:
      extra_libs: "mysql"
