name: Create New Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release, e.g. v1.1.0"
        required: true

jobs:
  bump-version:
    uses: PulsarFW/.github/.github/workflows/release.yml@main
    with:
      version: ${{ inputs.version }}
    secrets: inherit
